apiVersion: v1
kind: Secret
metadata:
  name: secrets-order-management
  labels:
    app: order-processor
data:
  # service bus queue level connection string needed
  servicebus-order-management-connectionstring: <service_bus_queue_connectionstring>

---

apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-servicebus-auth
spec:
  secretTargetRef:
  - parameter: connection
    name: secrets-order-management
    key: servicebus-order-management-connectionstring

---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-servicebus-queue-scaledobject
  namespace: keda-test
spec:
  scaleTargetRef:
    name: test-deployment
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: hpa-queue
      messageCount: "5"
    authenticationRef:
        name: azure-servicebus-auth